services:
  db:
    image: mysql
    container_name: "mysql-ms"
    ports:
      - "3306:3306"
    extends:
      service: microservice-mysql-config
      file: common-config.yml

  configserverms:
    image: "timsam31/configserver:v6"
    container_name: configserver
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    extends:
      service: microservice-base-config
      file: common-config.yml
    environment:
      SPRING_APPLICATION_NAME: "configserverms"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  eurekaserver:
    image: "timsam31/eureka:v6"
    container_name: eureka-ms
    ports:
      - "8070:8070"
    extends:
      service: microservice-eureka-config
      file: common-config.yml
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    depends_on:
      configserverms:
        condition: service_healthy

  accounts:
    image: "timsam31/accounts:v6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    extends:
      service: microservice-config
      file: common-config.yml
    depends_on:
      configserverms:
        condition: service_healthy
      db:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"


  loans:
    image: "timsam31/loans:v6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    extends:
      service: microservice-config
      file: common-config.yml
    depends_on:
      configserverms:
        condition: service_healthy
      db:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"

  cards:
    image: "timsam31/cards:v6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    extends:
      service: microservice-config
      file: common-config.yml
    depends_on:
      configserverms:
        condition: service_healthy
      db:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"

networks:
  timbank:
    driver: "bridge"