server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: root
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8070/eureka/
    fetch-registry: true
    register-with-eureka: true
info:
  app:
    name: "Tim bank"
    description : "Tim Bank Accounts micro-service"
    version: "1.0"
